### ISSUE TITLE
Compatibility Issue with Woocommerce v3.5.5

### ISSUE THREAD

**Issue by Awerta** [lukecav/code-snippets-wp-speed-up#1]
Thank you for your plugin. but This snippet is not compatible with Woocommerce v3.5.5 :
hide-out-of-stock-products-in-related-products-for-woocommerce.code-snippets.xml

**Comment by Awerta** [comment]
Thank you for your plugin. but This snippet is not compatible with Woocommerce v3.5.5

**Comment by lukecav** [comment]
Let me take a look.
https://raw.githubusercontent.com/lukecav/code-snippets-wp-speed-up/master/hide-out-of-stock-products-in-related-products-for-woocommerce.code-snippets.xml

**Comment by moistreet** [comment]
PLease check the compatibility issue ...

**Comment by lukecav** [comment]
I will when I have a moment.

**Comment by lukecav** [comment]
Updated.
https://raw.githubusercontent.com/lukecav/code-snippets-wp-speed-up/master/hide-out-of-stock-products-in-related-products-for-woocommerce.code-snippets.json

**Comment by lukecav** [comment]
https://wordpress.stackexchange.com/questions/334909/how-to-hide-out-of-stock-products-in-related-products-via-custom-query-in-woocom
