### ISSUE TITLE
May I contribute?

### ISSUE THREAD

**Issue by paketos** [lukecav/code-snippets-wp-speed-up#2]
Hi

This is not an issue, rather a contribution question. Since I am a complete noob on github, I am not sure if this is the correct way of asking this. I have made a snippet which I would like to share for you and anyone following you. 
This snippet is not hiding the count of products in product category listings, it is rather adding the string "product" or "products" based on the number of product within a category. The appended string is also translatable, meaning that it will show the string in the front-end language.
In my website I have also modified the style of `mark.count` and looks according to my needs, therefore one might need to style this element.
Please let me know if you would like me to share this here.
Thanx

**Comment by lukecav** [comment]
@paketos 

If you can share the code snippet in a Gist, I can add it using the Code Snippets plugin on a dev site and export the code, then upload the code into this repo.

**Comment by paketos** [comment]
Thanx for your reply, please find the code snippet here: https://gist.github.com/paketos/cd44963da0680a9120b1c2b32fb44e28.
Even though this is working, please check if there are any issues with the code.
Thanx

**Comment by lukecav** [comment]
https://github.com/lukecav/code-snippets-wp-speed-up/commit/f0536dd4895780b5b413fdd714793ffbbaf74a4c
